version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    command: /bin/bash -c "source /AgrisarthiProject/venv/bin/activate && python /AgrisarthiProject/agrisarthi/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/AgrisarthiProject/agrisarthi
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: mysql:5.7
    container_name: agrisarthi-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrisarathi
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
